// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_READYSIGNAL_H_
#define FLATBUFFERS_GENERATED_READYSIGNAL_H_

#include "flatbuffers/flatbuffers.h"

enum ReadySignal : int8_t {
  ReadySignal_Read = 0,
  ReadySignal_Written = 1,
  ReadySignal_Reading = 2,
  ReadySignal_Writing = 3,
  ReadySignal_MIN = ReadySignal_Read,
  ReadySignal_MAX = ReadySignal_Writing
};

inline const ReadySignal (&EnumValuesReadySignal())[4] {
  static const ReadySignal values[] = {
    ReadySignal_Read,
    ReadySignal_Written,
    ReadySignal_Reading,
    ReadySignal_Writing
  };
  return values;
}

inline const char * const *EnumNamesReadySignal() {
  static const char * const names[5] = {
    "Read",
    "Written",
    "Reading",
    "Writing",
    nullptr
  };
  return names;
}

inline const char *EnumNameReadySignal(ReadySignal e) {
  if (flatbuffers::IsOutRange(e, ReadySignal_Read, ReadySignal_Writing)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReadySignal()[index];
}

#endif  // FLATBUFFERS_GENERATED_READYSIGNAL_H_
